// Generated by gencpp from file app_loader/AppLoadResponse.msg
// DO NOT EDIT!


#ifndef APP_LOADER_MESSAGE_APPLOADRESPONSE_H
#define APP_LOADER_MESSAGE_APPLOADRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace app_loader
{
template <class ContainerAllocator>
struct AppLoadResponse_
{
  typedef AppLoadResponse_<ContainerAllocator> Type;

  AppLoadResponse_()
    : success(false)  {
    }
  AppLoadResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::app_loader::AppLoadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_loader::AppLoadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AppLoadResponse_

typedef ::app_loader::AppLoadResponse_<std::allocator<void> > AppLoadResponse;

typedef boost::shared_ptr< ::app_loader::AppLoadResponse > AppLoadResponsePtr;
typedef boost::shared_ptr< ::app_loader::AppLoadResponse const> AppLoadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::app_loader::AppLoadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::app_loader::AppLoadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::app_loader::AppLoadResponse_<ContainerAllocator1> & lhs, const ::app_loader::AppLoadResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::app_loader::AppLoadResponse_<ContainerAllocator1> & lhs, const ::app_loader::AppLoadResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace app_loader

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::app_loader::AppLoadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::app_loader::AppLoadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::app_loader::AppLoadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::app_loader::AppLoadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app_loader::AppLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app_loader::AppLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::app_loader::AppLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::app_loader::AppLoadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::app_loader::AppLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "app_loader/AppLoadResponse";
  }

  static const char* value(const ::app_loader::AppLoadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::app_loader::AppLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::app_loader::AppLoadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::app_loader::AppLoadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AppLoadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::app_loader::AppLoadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::app_loader::AppLoadResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APP_LOADER_MESSAGE_APPLOADRESPONSE_H
