// Generated by gencpp from file app_loader/AppUnloadRequest.msg
// DO NOT EDIT!


#ifndef APP_LOADER_MESSAGE_APPUNLOADREQUEST_H
#define APP_LOADER_MESSAGE_APPUNLOADREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace app_loader
{
template <class ContainerAllocator>
struct AppUnloadRequest_
{
  typedef AppUnloadRequest_<ContainerAllocator> Type;

  AppUnloadRequest_()
    : name()
    , type()  {
    }
  AppUnloadRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::app_loader::AppUnloadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app_loader::AppUnloadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AppUnloadRequest_

typedef ::app_loader::AppUnloadRequest_<std::allocator<void> > AppUnloadRequest;

typedef boost::shared_ptr< ::app_loader::AppUnloadRequest > AppUnloadRequestPtr;
typedef boost::shared_ptr< ::app_loader::AppUnloadRequest const> AppUnloadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::app_loader::AppUnloadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::app_loader::AppUnloadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::app_loader::AppUnloadRequest_<ContainerAllocator1> & lhs, const ::app_loader::AppUnloadRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::app_loader::AppUnloadRequest_<ContainerAllocator1> & lhs, const ::app_loader::AppUnloadRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace app_loader

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::app_loader::AppUnloadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::app_loader::AppUnloadRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app_loader::AppUnloadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f11915b22b276d2fb5587b35400289d";
  }

  static const char* value(const ::app_loader::AppUnloadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f11915b22b276d2ULL;
  static const uint64_t static_value2 = 0xfb5587b35400289dULL;
};

template<class ContainerAllocator>
struct DataType< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "app_loader/AppUnloadRequest";
  }

  static const char* value(const ::app_loader::AppUnloadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string type\n"
;
  }

  static const char* value(const ::app_loader::AppUnloadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AppUnloadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::app_loader::AppUnloadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::app_loader::AppUnloadRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APP_LOADER_MESSAGE_APPUNLOADREQUEST_H
