// Generated by gencpp from file gsdf_msgs/LeaveSwarm.msg
// DO NOT EDIT!


#ifndef GSDF_MSGS_MESSAGE_LEAVESWARM_H
#define GSDF_MSGS_MESSAGE_LEAVESWARM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gsdf_msgs
{
template <class ContainerAllocator>
struct LeaveSwarm_
{
  typedef LeaveSwarm_<ContainerAllocator> Type;

  LeaveSwarm_()
    : robot_id(0)
    , swarm_id(0)  {
    }
  LeaveSwarm_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , swarm_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;

   typedef int32_t _swarm_id_type;
  _swarm_id_type swarm_id;





  typedef boost::shared_ptr< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> const> ConstPtr;

}; // struct LeaveSwarm_

typedef ::gsdf_msgs::LeaveSwarm_<std::allocator<void> > LeaveSwarm;

typedef boost::shared_ptr< ::gsdf_msgs::LeaveSwarm > LeaveSwarmPtr;
typedef boost::shared_ptr< ::gsdf_msgs::LeaveSwarm const> LeaveSwarmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator1> & lhs, const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.swarm_id == rhs.swarm_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator1> & lhs, const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gsdf_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03a316fe2f23659ac2ee7cc9f35ab40f";
  }

  static const char* value(const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03a316fe2f23659aULL;
  static const uint64_t static_value2 = 0xc2ee7cc9f35ab40fULL;
};

template<class ContainerAllocator>
struct DataType< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gsdf_msgs/LeaveSwarm";
  }

  static const char* value(const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot_id\n"
"int32 swarm_id\n"
;
  }

  static const char* value(const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.swarm_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeaveSwarm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gsdf_msgs::LeaveSwarm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gsdf_msgs::LeaveSwarm_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "swarm_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.swarm_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GSDF_MSGS_MESSAGE_LEAVESWARM_H
